# 💻 예외처리(Exception)

## ✏️ 프로그램 오류

- 오류의 종류
  > 1.  컴파일 에러 : 프로그램의 실행을 막는 **소스 상의 문법 에러**, 소스 구문을 수정하여 해결
  > 2.  런타임 에러 : 입력 값이 틀렸거나, 배열의 인덱스 범위를 벗어났거나, 계산식의 오류등 실행중에 발생하는 에러 주로 프로그래머의 잘못이 대부분으로 예외처리보다 코드를 수정해야 하는 경우가 많음
  > 3.  시스템 에러 : 컴퓨터 오작동으로 인한 에러, 소스 구문으로 해결 불가
- 오류 해결 방법
  > 소스 수정으로 해결 가능한 에러를 예외(Exception)라고 하는데 이러한 예외 상황(예측 가능한 에러) 구문을 처리 하는 방법인 예외처리를 통해 해결

## ✏️ 예외 클래스 계층 구조

> Excepion과 Error 클래스 모두 Object 클래스의 자손  
> 모든 예외의 최상위 클래스는 Excetion  
> 클래스 반드시 예외 처리 해 주어야 하는 Checked Exception과 예외 처리 해주지 않아도 괜찮은 Unchecked Exception으로 나뉜다.

![예외 클래스 계층 구조](https://user-images.githubusercontent.com/105089699/183319351-c73f6fd1-79af-4147-bdcf-5131d5805a9f.png)

## ✏️ 예외처리

- RuntimeException

  > RuntimeException과 그 후손 클래스들은 전부 Unchecked Exception으로 프로그래머의 잘못이 대부분이기 때문에 예외처리보다 코드를 수정해야 하는 경우가 많음

- RuntimeExcepyion 후손 클래스

  - ArithmeticException  
    `0으로 나누는 경우 발생 if문으로 나누는 수가 0인지 검사`

  - ArrayIndexOutOfBoundsException  
    `배열의 index범위를 넘어서 참조하는 경우 배열명.length를 사용하여 배열의 범위 확인`
  - NegativeArraySizeException  
    `배열 크기를 음수로 지정한 경우 발생 배열 크기를 0보다 크게 지정해야 함`
  - ClassCastException  
    `Cast연산자 사용 시 타입 오류 instanceof연산자로 객체타입 확인 후 cast연산`
  - NullPointerException  
    `Null인 참조 변수로 객체 멤버 참조 시도 시 발생 객체 사용 전에 참조 변수가 null인지 확인`

- Exception 확인하기  
  `Java API Document에서 해당 클래스에 대한 생성자나 메소드를 검색하면 그 메소드가 어떤 Exception을 발생시킬 가능성이 있는지 확인 가능. 해당 메소드를 사용하려면 반드시 뒤에 명시된 예외 클래스를 처리해야 함`

## ✏️ 예외처리 방법

1. Exception 처리를 호출한 메소드에게 위임 - throws문

   > 메소드 선언시 throws ExceptionName문을 추가하여 호출한 상위 메소드에게 처리 위임  
   > 계속 위임하면 main()메소드까지 위임하게 되고 거기서 처리되지 않는 경우 비정상 종료 한번은 직접 처리 해야한다.

2. Exception이 발생한 곳에서 직접 처리 - try~catch문
   > - try : exception 발생할 가능성이 있는 코드를 안에 기술
   > - catch : try 구문에서 exception 발생 시 해당하는 exception을 어떻게 처리 할 것인지 기술  
   >   여러 개의 exception 처리가 가능하나 exception간의 상속 관계 고려
   > - finally : exception 발생 여부와 관계없이 꼭 처리해야 하는 로직 기술

```JAVA
   public class ThrowsController {
   	public void method1() {
   		System.out.println("method1() 시작...");
      try{
   		  method2();	// method2에서 위임 받은 예외 발생
      }catch{
        System.out.println("예외 처리");
      }finally {
			  System.out.println("예외 발생 여부와 상관 없이 무조건 수행 (finally)");
		  }
   		System.out.println("method1() 끝...");
   	}

   	public void method2() throws Exception {	// 호출한 상위 메소드로 위임
   		System.out.println("method2() 시작...");
   		method3();	// method3에서 위임 받은 예외 발생
   		System.out.println("method2() 끝...");
   	}

   	public void method3() throws Exception {	// 호출한 상위 메소드로 위임
   		System.out.println("method3() 시작...");
   		throw new Exception();	// 예외 발생
   		// throw : 예외 강제 발생(throws와 다름)
   		// throw로 예외 강제 발생시 try~catch 사용 X throws로 위임시킨다.
   //		System.out.println("method3() 끝..."); // Unreachable code : 위에 예외가 발생한 코드가 있으면 연결되지 않는다.
   	}
   }
```
